# Generated by Django 3.1.5 on 2021-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpassword',
            name='identifiant',
            field=models.CharField(blank=True, default='3325096772319295', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminpassword',
            name='password',
            field=models.CharField(blank=True, default='4797124677073621', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(default='7237084006', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(default='2730872307', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='content',
            field=models.CharField(default='6803674557', max_length=32, unique=True),
        ),
    ]
