# Generated by Django 3.1.5 on 2021-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_auto_20210124_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(default='3426325237', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(default='2548923227', max_length=10, unique=True),
        ),
    ]
