# Generated by Django 3.1.5 on 2021-07-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_auto_20210708_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpassword',
            options={'verbose_name': 'Mot de passe admin', 'verbose_name_plural': 'Mots de passe admin'},
        ),
        migrations.AlterField(
            model_name='adminpassword',
            name='identifiant',
            field=models.CharField(blank=True, default='0705251053020070', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminpassword',
            name='password',
            field=models.CharField(blank=True, default='0915368666986531', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(default='6297695600', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(default='2790335187', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='content',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
