# Generated by Django 3.1.5 on 2021-07-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_auto_20210708_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpassword',
            name='identifiant',
            field=models.CharField(blank=True, default='8756464105887446', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminpassword',
            name='password',
            field=models.CharField(blank=True, default='1898004847377467', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(default='2437811578', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(default='3242659671', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='content',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
