# Generated by Django 3.1.5 on 2021-06-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_auto_20210607_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(default='1660566533', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(default='9938453354', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='content',
            field=models.CharField(default='6566523664', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, default='9409194061502421', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='1838702385069591', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entreprise.key')),
            ],
            options={
                'verbose_name': 'Clé',
                'verbose_name_plural': 'Clés',
            },
        ),
    ]
