# Generated by Django 3.1.5 on 2021-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='code',
            field=models.CharField(default='0916671047', max_length=10, unique=True),
        ),
    ]
